[status]
separator_open  = ""
separator_close = ""

[filetype]
rules = [
	{ mime = "text/*", fg = "#0a84ff" }, # Archivos de texto en azul Apple
	{ mime = "application/json", fg = "#ffd60a" }, # JSON en amarillo Apple
	{ url = "*.sh", fg = "#30d158" }, # Scripts en verde Apple
]
