ipc = true
splash = false

preload = /home/jorge/.config/hypr/wallpaper.png

wallpaper = eDP-1,/home/jorge/.config/hypr/wallpaper.png
wallpaper = HDMI-A-1,/home/jorge/.config/hypr/wallpaper.png
wallpaper = DP-1,/home/jorge/.config/hypr/wallpaper.png
wallpaper = ,/home/jorge/.config/hypr/wallpaper.png

