#  _   _                 _            _    
# | | | |               | |          | |   
# | |_| |_   _ _ __  ___| | ___   ___| | __
# |  _  | | | | '_ \/ __| |/ _ \ / __| |/ /
# | | | | |_| | |_) \__ \ | (_) | (__|   < 
# \_| |_/\__, | .__/|___/_|\___/ \___|_|\_\
#         __/ | |                          
#        |___/|_|                          
# 
# Configuración de bloqueo autónoma y elegante

background {
    monitor =
    path = /home/jorge/.config/hypr/wallpaper_real.png
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# HORA
label {
    monitor =
    text = cmd[update:1000] echo "$(/usr/bin/date +"%H:%M")"
    color = rgba(205, 214, 244, 0.9)
    font_size = 90
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 150
    halign = center
    valign = center
}

# FECHA
label {
    monitor =
    text = cmd[update:1000] echo "$(/usr/bin/date +"%A, %d de %B de %Y")"
    color = rgba(166, 173, 200, 0.8)
    font_size = 20
    font_family = Cantarell
    position = 0, 70
    halign = center
    valign = center
}

# CAMPO DE CONTRASEÑA
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 setter alignment
    outer_color = rgba(64, 47, 163, 0.9) # Usando el color azul/morado principal
    inner_color = rgba(1, 15, 51, 0.7)   # Usando el fondo oscuro principal
    font_color = rgb(205, 214, 244)
    fade_on_empty = true
    fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
    placeholder_text = <i>Introduce tu contraseña...</i> # Text rendered in the input box when it's empty.
    hide_input = false
    rounding = -1 # -1 means complete rounding (circle)
    check_color = rgb(166, 227, 161)
    fail_color = rgb(243, 139, 168) # if checking failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
    invert_numlock = false # change color if numlock is off
    swap_font_color = false # see below

    position = 0, -50
    halign = center
    valign = center
}
