#  _   _                 _            _    
# | | | |               | |          | |   
# | |_| |_   _ _ __  ___| | ___   ___| | __
# |  _  | | | | '_ \/ __| |/ _ \ / __| |/ /
# | | | | |_| | |_) \__ \ | (_) | (__|   < 
# \_| |_/\__, | .__/|___/_|\___/ \___|_|\_\
#         __/ | |                          
#        |___/|_|                          
# 
# Configuración de bloqueo autónoma y elegante

background {
    monitor =
    path = /home/jorge/.config/hypr/wallpaper_real.png
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# HORA
label {
    monitor =
    text = cmd[update:1000] echo "$(/usr/bin/date +"%H:%M")"
    color = rgba(245, 245, 247, 0.95)
    font_size = 90
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 150
    halign = center
    valign = center
}

# FECHA
label {
    monitor =
    text = cmd[update:1000] echo "$(/usr/bin/date +"%A, %d de %B de %Y")"
    color = rgba(142, 142, 147, 0.90)
    font_size = 20
    font_family = Cantarell
    position = 0, 70
    halign = center
    valign = center
}

# CAMPO DE CONTRASEÑA
input-field {
    monitor =
    size = 260, 48
    outline_thickness = 2
    dots_size = 0.30
    dots_spacing = 0.20
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(10, 132, 255, 0.8) # Acento oficial Apple Blue
    inner_color = rgba(28, 28, 30, 0.85)  # Fondo Apple Space Gray translúcido
    font_color = rgb(245, 245, 247)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Introduce tu contraseña...</i>
    hide_input = false
    rounding = -1
    check_color = rgb(48, 209, 88)   # Apple Green
    fail_color = rgb(255, 69, 58)    # Apple Red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 200
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
    invert_numlock = false # change color if numlock is off
    swap_font_color = false # see below

    position = 0, -50
    halign = center
    valign = center
}
