
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hypr.land/Configuring/Monitors/
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2

# Configuración del monitor principal (eDP-1)
# Sintaxis: monitor = nombre, resolución@tasa_refresco, posición, escala
# Si deseas que todo se vea más pequeño (escala 100%):
monitor = eDP-1, preferred, auto, 1

# O si prefieres un tamaño intermedio como 1.25 (125%):
# monitor = eDP-1, preferred, auto, 1.25

