

$GTK_THEME = Catppuccin-Mocha
$ICON_THEME = Tela-circle-dracula
$COLOR_SCHEME = prefer-dark

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(1d4ed8ff)
    col.inactive_border = rgba(313244ff)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(1d4ed8ff)
    col.border_inactive = rgba(313244ff)
    col.border_locked_active = rgba(1d4ed8ff)
    col.border_locked_inactive = rgba(313244ff)
}

decoration {
    rounding = 10
    shadow:enabled = false

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}
